name: R-Master

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: checkout r-server
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GIT_TOKEN }}
       - name: initialization r-server
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email  ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repository
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.GIT_REPO }} r-host
       - name: running r-server server
         timeout-minutes: 250
         continue-on-error: true
         run: |
           cd r-host
           docker build . -t r-host
           docker run r-host     
